### ISSUE TITLE
Wrong import. Remove *.pyc. Missing .gitignore

### ISSUE THREAD

**Issue by vietvudanh** [pythonvietnam/onlinequiz#2]
[https://github.com/pythonvietnam/onlinequiz/blob/master/app/**init**.py](onlinequiz/app/__init__.py)
Have one not correct line:

`from flaskext.uploads import UploadSet, IMAGES, configure_uploads`

It should be:

`from flask.ext.uploads import UploadSet, IMAGES, configure_uploads`

By the way, need to remove and ignore all *.pyc file.

Finally, does this project is still in progress or not?

**Comment by khanhnnvn** [comment]
The project not process.

**Comment by vietvudanh** [comment]
OK, thank you.
